#!/bin/python3.8.2
print("This is Bob, and he be groovin")
print("        / \         ")
print("        \_/         ")
print("         |          ")
print("        /|\         ")
print("       / | \        ")
print("      /  |  \       ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
import time
import os
time.sleep(1)
os.system('clear')
print("        / \         ")
print("        \_/         ")
print("         |          ")
print("        /|\         ")
print("     \_/ | \_/      ")
print("         |          ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
time.sleep(0.1)
os.system('clear')
print("        / \         ")
print("        \_/         ")
print("         |          ")
print("    \___/|\___/         ")
print("         |          ")
print("         |          ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
for x in range(20):
    time.sleep(0.1)
    os.system('clear')
    print("        / \         ")
    print("        \_/         ")
    print("         |          ")
    print("    ¯¯¯¯¯|¯¯¯¯¯     ")
    print("         |          ")
    print("         |          ")
    print("         |          ")
    print("         /\         ")
    print("        /  \        ")
    print("       /    \       ")
    time.sleep(0.1)
    os.system('clear')
    print("       / \         ")
    print("   \   \_/         ")
    print("    \    |          ")
    print("      ¯¯¯|¯¯¯\      ")
    print("         |    \     ")
    print("         |          ")
    print("         |          ")
    print("         /\         ")
    print("       _/  \        ")
    print("            \       ")
    time.sleep(0.1)
    os.system('clear')
    print("    \   / \         ")
    print("     \  \_/         ")
    print("      \  |          ")
    print("       ¯¯|¯¯\       ")
    print("         |   \      ")
    print("         |    \     ")
    print("         |          ")
    print("       __/\         ")
    print("           \        ")
    print("            \       ")
    time.sleep(0.1)
    os.system('clear')
    print("         / \         ")
    print("   \     \_/         ")
    print("    \    |          ")
    print("      ¯¯¯|¯¯¯\      ")
    print("         |    \     ")
    print("         |          ")
    print("         |          ")
    print("         /\         ")
    print("       _/  \        ")
    print("            \       ")
    time.sleep(0.1)
    os.system('clear')
    print("        / \         ")
    print("        \_/         ")
    print("         |          ")
    print("    ¯¯¯¯¯|¯¯¯¯¯     ")
    print("         |          ")
    print("         |          ")
    print("         |          ")
    print("         /\         ")
    print("        /  \        ")
    print("       /    \       ")
    time.sleep(0.1)
    os.system('clear')
    print("       / \         ")
    print("       \_/   /     ")
    print("         |   /      ")
    print("     /¯¯¯|¯¯¯       ")
    print("    /    |          ")
    print("         |          ")
    print("         |          ")
    print("         /\         ")
    print("        /  \_       ")
    print("       /            ")
    time.sleep(0.1)
    os.system('clear')
    print("        / \   /     ")
    print("        \_/  /      ")
    print("         |  /       ")
    print("      /¯¯|¯¯        ")
    print("     /   |          ")
    print("    /    |          ")
    print("         |          ")
    print("         /\__       ")
    print("        /           ")
    print("       /            ")
    time.sleep(0.1)
    os.system('clear')
    print("         / \         ")
    print("         \_/   /     ")
    print("         |   /      ")
    print("     /¯¯¯|¯¯¯       ")
    print("    /    |          ")
    print("         |          ")
    print("         |          ")
    print("         /\         ")
    print("        /  \_       ")
    print("       /            ")
time.sleep(0.1)
os.system('clear')
print("        / \         ")
print("        \_/         ")
print("         |          ")
print("    ¯¯¯¯¯|¯¯¯¯¯     ")
print("         |          ")
print("         |          ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
time.sleep(0.1)
os.system('clear')
print("       / \         ")
print("       \_/         ")
print("         |          ")
print("    \___/|\___/     ")
print("         |          ")
print("         |          ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
time.sleep(0.1)
os.system('clear')
print("        / \         ")
print("        \_/         ")
print("         |          ")
print("        /|\         ")
print("     \_/ | \_/      ")
print("         |          ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
time.sleep(0.1)
os.system('clear')
print("        / \         ")
print("        \_/         ")
print("         |          ")
print("        /|\         ")
print("       / | \        ")
print("      /  |  \       ")
print("         |          ")
print("         /\         ")
print("        /  \        ")
print("       /    \       ")
